import { Level } from '../types';

export const DEFAULT_LEVELS: Level[] = [
  {
    id: 1,
    title: "Level 1: Beginner 1-Digit",
    description: "Basic 1-digit addition and subtraction across 5 rows (Numbers 1-9).",
    digits: 1,
    rows: 5,
    minVal: 1,
    maxVal: 9,
    allowNegative: false,
    timeLimitSeconds: 180,
    passingPct: 70,
  },
  {
    id: 2,
    title: "Level 2: Intermediate 1-Digit",
    description: "Faster 1-digit calculations with mixed signs and larger sums.",
    digits: 1,
    rows: 5,
    minVal: 1,
    maxVal: 9,
    allowNegative: true,
    timeLimitSeconds: 180,
    passingPct: 70,
  },
  {
    id: 3,
    title: "Level 3: Advanced 1-Digit Speed",
    description: "Complex 1-digit bead manipulation drill with rapid sequences.",
    digits: 1,
    rows: 5,
    minVal: 2,
    maxVal: 9,
    allowNegative: true,
    timeLimitSeconds: 150,
    passingPct: 70,
  },
  {
    id: 4,
    title: "Level 4: 2-Digit Foundation",
    description: "Introduction to 2-digit numbers (10-49) across 5 rows.",
    digits: 2,
    rows: 5,
    minVal: 10,
    maxVal: 49,
    allowNegative: false,
    timeLimitSeconds: 180,
    passingPct: 70,
  },
  {
    id: 5,
    title: "Level 5: Intermediate 2-Digit",
    description: "Standard 2-digit numbers (10-99) with mixed addition and subtraction.",
    digits: 2,
    rows: 5,
    minVal: 10,
    maxVal: 99,
    allowNegative: true,
    timeLimitSeconds: 180,
    passingPct: 70,
  },
  {
    id: 6,
    title: "Level 6: Advanced 2-Digit Master",
    description: "Challenging 2-digit sums with tight timing and complex complements.",
    digits: 2,
    rows: 5,
    minVal: 20,
    maxVal: 99,
    allowNegative: true,
    timeLimitSeconds: 150,
    passingPct: 70,
  },
  {
    id: 7,
    title: "Level 7: 3-Digit Expert",
    description: "Advanced 3-digit numbers (100-499) for elite abacus mental masters.",
    digits: 3,
    rows: 5,
    minVal: 100,
    maxVal: 499,
    allowNegative: true,
    timeLimitSeconds: 180,
    passingPct: 70,
  },
  {
    id: 8,
    title: "Level 8: Grandmaster Abacus Test",
    description: "Ultimate 3-digit speed test across 5 rows of complex values.",
    digits: 3,
    rows: 5,
    minVal: 150,
    maxVal: 999,
    allowNegative: true,
    timeLimitSeconds: 150,
    passingPct: 70,
  },
];
